In [1]:
import pandas as pd
from itertools import combinations
from collections import Counter

In [2]:
# Load the dataset
df = pd.read_excel("D:\\DS Assignment\\Association Rules\\Association Rules\\Online retail.xlsx")

# Display first rows
df.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [3]:
# Convert dataset into transaction list

col = df.columns[0]

transactions = df[col].astype(str).apply(
    lambda x: [item.strip().lower() for item in x.split(',') if item.strip()!='']
).tolist()

print("Total Transactions:", len(transactions))

Total Transactions: 7500

In [4]:
min_support = 0.01
min_count = int(min_support * len(transactions))

item_counts = Counter()

for t in transactions:
    item_counts.update(set(t))

frequent_items = {item for item, count in item_counts.items() if count >= min_count}

print("Frequent 1-itemsets:", len(frequent_items))

Frequent 1-itemsets: 75

In [5]:
pair_counts = Counter()

for t in transactions:
    for pair in combinations(set(t), 2):
        pair_counts[pair] += 1

frequent_pairs = {pair:count for pair,count in pair_counts.items() if count >= min_count}

print("Frequent 2-itemsets:", len(frequent_pairs))

Frequent 2-itemsets: 142

In [6]:
rules = []

for (item1, item2), count in frequent_pairs.items():
    
    support = count / len(transactions)
    
    support_item1 = item_counts[item1] / len(transactions)
    support_item2 = item_counts[item2] / len(transactions)
    
    confidence = support / support_item1
    
    lift = confidence / support_item2
    
    if confidence >= 0.4:
        rules.append([item1, item2, support, confidence, lift])

In [7]:
rules_df = pd.DataFrame(
    rules,
    columns=["Item A", "Item B", "Support", "Confidence", "Lift"]
)

rules_df.sort_values(by="Lift", ascending=False).head(10)

        Item A         Item B   Support  Confidence      Lift
0  ground beef  mineral water  0.040000    0.407056  1.708404
1    olive oil  mineral water  0.026533    0.403651  1.694115

In [8]:
rules_df.to_csv("association_rules_output.csv", index=False)